### ISSUE TITLE
vzlogger segfault on OpenWRT v22.03.2

### ISSUE THREAD

**Issue by perrin-1** [franzflasch/vzlogger-openwrt#1]
Using recent OpenWRT and your repo I was able to compile and install vzlogger successfully on OpenWRT.
When running with real config, vzlogger segfaults as soon as the first readings arrive

OpenWRT Running on a Raspberry Pi Model B
Version: Linux version 5.10.146 (compile@phoebe) (arm-openwrt-linux-muslgnueabi-gcc (OpenWrt GCC 11.2.0 r19803-9a599fee93) 11.2.0, GNU ld (GNU Binutils) 2.37) #0 Fri Oct 14 22:44:41 2022

Log:
`
root@PowerMeterPI:~/vzlogger# vzlogger -f
[Jan 08 12:35:31][main] vzlogger v0.8.1 based on tags/v22.03.2-0-gea845f76ea from Sat, 15 Oct 2022 14:45:57 +0200 started.
[Jan 08 12:35:31][mtr0] Creating new meter with protocol sml.
[Jan 08 12:35:31][sml]  pullseq len:0 found
[Jan 08 12:35:31][mtr0] Meter configured, enabled.
[Jan 08 12:35:31]       New meter initialized (protocol=sml)
[Jan 08 12:35:31]       Configure channel.
[Jan 08 12:35:31][chn0] New channel initialized (uuid=...000000 api=influxdb id=1-0:1.8.0)
[Jan 08 12:35:31]       Configure channel.
[Jan 08 12:35:31][chn1] New channel initialized (uuid=...000000 api=influxdb id=1-0:2.8.0)
[Jan 08 12:35:31]       Configure channel.
[Jan 08 12:35:31][chn2] New channel initialized (uuid=...000000 api=influxdb id=1-0:16.7.0)
[Jan 08 12:35:31]       Configure channel.
[Jan 08 12:35:31][chn3] New channel initialized (uuid=...000000 api=influxdb id=1-0:36.7.0)
[Jan 08 12:35:31]       Configure channel.
[Jan 08 12:35:31][chn4] New channel initialized (uuid=...000000 api=influxdb id=1-0:56.7.0)
[Jan 08 12:35:31]       Configure channel.
[Jan 08 12:35:31][chn5] New channel initialized (uuid=...000000 api=influxdb id=1-0:76.7.0)
[Jan 08 12:35:31][mtr1] Creating new meter with protocol sml.
[Jan 08 12:35:31][sml]  pullseq len:0 found
[Jan 08 12:35:31][mtr1] Meter configured, enabled.
[Jan 08 12:35:31]       New meter initialized (protocol=sml)
[Jan 08 12:35:31]       Configure channel.
[Jan 08 12:35:31][chn6] New channel initialized (uuid=...000000 api=influxdb id=1-0:1.8.0)
[Jan 08 12:35:31]       Configure channel.
[Jan 08 12:35:31][chn7] New channel initialized (uuid=...000000 api=influxdb id=1-0:2.8.0)
[Jan 08 12:35:31]       Configure channel.
[Jan 08 12:35:31][chn8] New channel initialized (uuid=...000000 api=influxdb id=1-0:16.7.0)
[Jan 08 12:35:31]       Configure channel.
[Jan 08 12:35:31][chn9] New channel initialized (uuid=...000000 api=influxdb id=1-0:36.7.0)
[Jan 08 12:35:31]       Configure channel.
[Jan 08 12:35:31][chn10]New channel initialized (uuid=...000000 api=influxdb id=1-0:56.7.0)
[Jan 08 12:35:31]       Configure channel.
[Jan 08 12:35:31][chn11]New channel initialized (uuid=...000000 api=influxdb id=1-0:76.7.0)
[Jan 08 12:35:31]       Have 2 meters.
[Jan 08 12:35:31][main] log level is 15
[Jan 08 12:35:31][main] local=1
[Jan 08 12:35:31]       Process not daemonized...
[Jan 08 12:35:31]       Opened logfile /var/log/vzlogger.log
[Jan 08 12:35:31][push] No pushDataServer defined.
[Jan 08 12:35:31][]     ===> Start meters
[Jan 08 12:35:31][mtr0] Meter connection established
[Jan 08 12:35:31][mtr0] Meter thread started
[Jan 08 12:35:31][mtr0] Meter is opened. Starting channels.

... LOG SKIPPED ...

[Jan 08 12:35:31][chn1] api InfluxDB will use default send_uuid true
[Jan 08 12:35:31][chn1] api InfluxDB will use default ssl_verifypeer true
[Jan 08 12:35:31][chn11]api InfluxDB will use default ssl_verifypeer true
[Jan 08 12:35:31][chn1] api InfluxDB using url openhab.<removed>:8086/write?db=vzlogger&precision=ms
[Jan 08 12:35:31][chn11]api InfluxDB using url openhab.<removed>:8086/write?db=vzlogger&precision=ms
[Jan 08 12:35:31][chn11]Using InfluxDB api
[Jan 08 12:35:31][chn1] Using InfluxDB api
[Jan 08 12:35:31][chn10]api InfluxDB using url openhab.<removed>:8086/write?db=vzlogger&precision=ms
[Jan 08 12:35:31][chn10]Using InfluxDB api
[Jan 08 12:35:32][mtr0] Got 10 new readings from meter:
[Jan 08 12:35:32][mtr0] Reading: id=1-0:1.8.0*255/ObisIdentifier:1-0:1.8.0*255 value=22595016.80 ts=1673181332037
[Jan 08 12:35:32][mtr0] Reading: id=1-0:1.8.1*255/ObisIdentifier:1-0:1.8.1*255 value=22595016.80 ts=1673181332037
[Jan 08 12:35:32][mtr0] Reading: id=1-0:1.8.2*255/ObisIdentifier:1-0:1.8.2*255 value=0.00 ts=1673181332037
[Jan 08 12:35:32][mtr0] Reading: id=1-0:2.8.0*255/ObisIdentifier:1-0:2.8.0*255 value=31539518.20 ts=1673181332037
[Jan 08 12:35:32][mtr0] Reading: id=1-0:2.8.1*255/ObisIdentifier:1-0:2.8.1*255 value=31539518.20 ts=1673181332037
[Jan 08 12:35:32][mtr0] Reading: id=1-0:2.8.2*255/ObisIdentifier:1-0:2.8.2*255 value=0.00 ts=1673181332037
[Jan 08 12:35:32][mtr0] Reading: id=1-0:16.7.0*255/ObisIdentifier:1-0:16.7.0*255 value=941.00 ts=1673181332037
[Jan 08 12:35:32][mtr0] Reading: id=1-0:36.7.0*255/ObisIdentifier:1-0:36.7.0*255 value=444.00 ts=1673181332037
[Jan 08 12:35:32][mtr0] Reading: id=1-0:56.7.0*255/ObisIdentifier:1-0:56.7.0*255 value=106.00 ts=1673181332037
[Jan 08 12:35:32][mtr0] Reading: id=1-0:76.7.0*255/ObisIdentifier:1-0:76.7.0*255 value=390.00 ts=1673181332037
Segmentation fault
`

**Comment by franzflasch** [comment]
Unfortunately I can not test this on a real smartmeter, because mine is not supported by vzlogger. I realized this after creating the openwrt package. So I am afraid I can not really help debugging this.

But I would try to update vzlogger to a newer revision, maybe this issue is already fixed upstream. You can do this by modifying the openwrt Makefile: https://github.com/franzflasch/vzlogger-openwrt/blob/main/vzlogger/Makefile

The newest vzlogger revision seems to be 927c2634414b808797df4a1db6392c75516d6613

**Comment by perrin-1** [comment]
I tried newer versions, but they did not work either. 
What works is, using an older version of OpenWRT. All seems to be running fine on OpenWRT 19.07...

**Comment by franzflasch** [comment]
Ah OK. That's an interesting issue then...
